### PR TITLE
major changes

### PR DESCRIPTION
**Pull request by spaniakos**
hello octate, i have made some major changes to the library, i do not know if you want to add them to your repo or if thats too much changes for your library.

If you find these changes good and responable and you wish to add them, feel free to do so :D

thanks
spaniakos.

### CODE REVIEW

**Comment by spaniakos** [comment]
Hello .
I am planning to change the iv increment with an optional variable in the
header soon
Just informing you about the change.

**Comment by Octoate** [comment]
Hi spaniakos, 
finally I got some time to review the changes and everything seems to work fine. However I had to remove the padding array initialization in from the header file, because it caused a compile error in Arduino 1.0.6. This shouldn't be a problem, because you already initialize the array within the constructor of the DES class. It would be nice if you can check if my changes work on the RasPi and the Galileo board.

Good idea to change the IV increment behaviour with an optional variable. I am still a bit worried about the size of the lib, because its main aim is the Arduino. Currently the DesedeCBC example uses 12kb of 28kb on an Arduino Leonardo (v1.0.6). That's still acceptable, however using an Ethernet shield will nearly use the complete rest of the memory.

**Comment by spaniakos** [comment]
For sure i can test the changes .
I will also do the optional iv increment.
About the size it won't be a problem i think. But we can check it later
with small boards. After all we can exclude code with #if defined
statements in order to have less but still acceptable functionality with
the small boards.

Keep in mind that some kb of the memory are used from the core libraries
that are shared for all shields.

**Comment by Octoate** [comment]
You are right. I guess the optimisation can be done later if the functionality is there :-).

**Pull request merged**
